DROP TABLE MEMBER CASCADE CONSTRAINT;

CREATE TABLE BASKET(

	BASKET_ID NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(50) NOT NULL,
    GOODS_TITLE VARCHAR2(100) NOT NULL,
    BASKET_NUMBERS NUMBER NOT NULL,
    BASKET_VALIDITY VARCHAR2(2) DEFAULT ('1') NOT NULL,
    BASKET_PRICE NUMBER NOT NULL,
    GOODS_PRICE NUMBER NOT NULL,
    
    CONSTRAINT MEMBER_ENABLED_CHK CHECK (MEMBER_ENABLED IN ('1','2')),
    CONSTRAINT BASKET_FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
    CONSTRAINT BASKET_FK_GOODS_TITLE FOREIGN KEY(GOODS_TITLE) REFERENCES GOODS(GOODS_TITLE)
    CONSTRAINT BASKET_FK_GOODS_PRICE FOREIGN KEY(GOODS_PRICE) REFERENCES GOODS(GOODS_PRICE)
    ON DELETE CASCADE
);

INSERT INTO BASKET
VALUES(1,'quddnraka','TEST4입니다','메인사진','600','3','내용물임',SYSDATE);
select * from basket;